### ISSUE TITLE
[Feature Request] Add Date Picker to Track Progress by Custom Dates

### ISSUE THREAD

**Issue by prbhtkumr** [tilorenz/TimeProgressBar#1]
![Screenshot_20240312_231407](https://github.com/tilorenz/TimeProgressBar/assets/50882504/ace63040-8b0b-4657-b396-c0e83aca03f1)

**Comment by tilorenz** [comment]
As I wrote in the README, this would be good to have, but it looks like neither Qt Quick nor Kirigami currently has a date picker. I'll have to see if/when I get around to making my own.

**Comment by tilorenz** [comment]
Done and released.
