### ISSUE TITLE
[Feature Request] Add a toggle switch to see remaining time

### ISSUE THREAD

**Issue by kinoegit** [tilorenz/TimeProgressBar#2]
Hi and thanks for your nice work! My girlfriend is away for 6 weeks and I'm looking forward to her return.
Though it is nice to see how much time has passed, it would be great to see the remaining time dwindle. 
So maybe there might be a way to implement a switch to toggle between two different states?: 
1. bar to display the elapsed time (as it is now) or:
2. bar to display the remaining time (in a way that would be an 'inverted' bar)
Thank you anyway

**Comment by tilorenz** [comment]
glad you like it :)
implemented the reverse bar and made a release. you can also now use %r to show the remaining %.

**Comment by kinoegit** [comment]
Thanks for taking an interest and your time! 
I uninstalled the old and downloaded the new version but unfortunately it doesn't work for me.
Neither does it show a reversed bar after ticking the box _'show remaining rather than passed time'_ nor is %r replaced by the remaining percentage: %r%% shows only % no numbers

Edit: a restart did the job! Sorry for bothering and thanks for implementing that feature!

**Comment by tilorenz** [comment]
Weird, I just confirmed it works for me.
> I uninstalled the old and downloaded the new version

how did you install the new version?
can you try manually downloading it and then doing `kpackagetool6 -t Plasma/Applet  -u package.plasmoid`

**Comment by tilorenz** [comment]
you may also need to log out for the changes to apply

**Comment by kinoegit** [comment]
> Edit: a restart did the job! Sorry for bothering and thanks for implementing that feature!
