### ISSUE TITLE
Feature: Add Custom Daily time progress

### ISSUE THREAD

**Issue by drtobbyas** [tilorenz/TimeProgressBar#4]
First of all, I want to appreciate you for making this widget.

I would like to see a feature where someone can set a custom daily time progress. For instance, I want to be able to set time progress for work hours period (9am - 5pm) which repeats and resets every day. I know there is a functionality to set daily time progress but that only covers 24 hours period (12am - 12pm), it's not suitable for work hours period. 

It would also be nice if it can work weekly as well.

Thanks

**Comment by Lex-2008** [comment]
I totally agree with @drtobbyas that it's a nice little widget!

And I must admit that tracking percentage of working day was the first I thought about :) I did it for myself by cruelly editing the `contents/ui/main.qml` file and hardcoding start and end timestamps in the `getDayProgress()` function:

```diff
        function getDayProgress() {
                var now = new Date()
-               var start = new Date(now.getFullYear(), now.getMonth(), now.getDate())
-               var end = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1)
+               var start = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 30)
+               var end = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 17)
                //console.log("now:", now.toString(), ", start:", start.toString(), ", end:", end.toString())
                return (now - start) / (end - start)
        }
```

Adding it as a proper configurable option is quite a bit more work. I also wonder what @tilorenz think about how it should be implemented (if at all?): as a new top-level option (progress by calendar / custom dates / work hours), as a sub-option for "progress by day" option, or something else?

**Comment by tilorenz** [comment]
Right, I forgot about the first comment, sorry.
I think the get__progress functions should probably just take a start- and end offset.
Supporting something like "9 to 5, but only on work days" would be a bit more complicated, but I don't think that's really necessary.

**Comment by tilorenz** [comment]
Implemented the option on main branch, feel free to test it out

**Comment by tilorenz** [comment]
Done and released.
